% kidney recipient data
prop(recipient_1,recipient_city,vancouver).
prop(recipient_2,recipient_city,surrey).
prop(recipient_3,recipient_city,surrey).
prop(recipient_4,recipient_city,vancouver).
prop(recipient_5,recipient_city,vancouver).
prop(recipient_6,recipient_city,burnaby).
prop(recipient_7,recipient_city,vancouver).
prop(recipient_8,recipient_city,vancouver).
prop(recipient_9,recipient_city,surrey).
prop(recipient_10,recipient_city,vancouver).
prop(recipient_11,recipient_city,vancouver).
prop(recipient_12,recipient_city,richmond).
prop(recipient_13,recipient_city,burnaby).
prop(recipient_14,recipient_city,vancouver).
prop(recipient_15,recipient_city,vancouver).
prop(recipient_16,recipient_city,richmond).
prop(recipient_17,recipient_city,vancouver).
prop(recipient_18,recipient_city,richmond).
prop(recipient_19,recipient_city,burnaby).
prop(recipient_20,recipient_city,vancouver).
prop(recipient_21,recipient_city,burnaby).
prop(recipient_22,recipient_city,surrey).
prop(recipient_23,recipient_city,surrey).
prop(recipient_24,recipient_city,vancouver).
prop(recipient_25,recipient_city,vancouver).
prop(recipient_26,recipient_city,surrey).
prop(recipient_27,recipient_city,burnaby).
prop(recipient_28,recipient_city,surrey).
prop(recipient_29,recipient_city,vancouver).
prop(recipient_30,recipient_city,burnaby).

prop(recipient_1,recipient_blood_type,a).
prop(recipient_2,recipient_blood_type,b).
prop(recipient_3,recipient_blood_type,o).
prop(recipient_4,recipient_blood_type,b).
prop(recipient_5,recipient_blood_type,ab).
prop(recipient_6,recipient_blood_type,o).
prop(recipient_7,recipient_blood_type,a).
prop(recipient_8,recipient_blood_type,o).
prop(recipient_9,recipient_blood_type,b).
prop(recipient_10,recipient_blood_type,a).
prop(recipient_11,recipient_blood_type,a).
prop(recipient_12,recipient_blood_type,ab).
prop(recipient_13,recipient_blood_type,o).
prop(recipient_14,recipient_blood_type,o).
prop(recipient_15,recipient_blood_type,a).
prop(recipient_16,recipient_blood_type,a).
prop(recipient_17,recipient_blood_type,o).
prop(recipient_18,recipient_blood_type,o).
prop(recipient_19,recipient_blood_type,a).
prop(recipient_20,recipient_blood_type,b).
prop(recipient_21,recipient_blood_type,o).
prop(recipient_22,recipient_blood_type,b).
prop(recipient_23,recipient_blood_type,o).
prop(recipient_24,recipient_blood_type,b).
prop(recipient_25,recipient_blood_type,a).
prop(recipient_26,recipient_blood_type,o).
prop(recipient_27,recipient_blood_type,a).
prop(recipient_28,recipient_blood_type,o).
prop(recipient_29,recipient_blood_type,ab).
prop(recipient_30,recipient_blood_type,o).

prop(recipient_1,recipient_age,37).
prop(recipient_2,recipient_age,32).
prop(recipient_3,recipient_age,9).
prop(recipient_4,recipient_age,22).
prop(recipient_5,recipient_age,46).
prop(recipient_6,recipient_age,12).
prop(recipient_7,recipient_age,30).
prop(recipient_8,recipient_age,59).
prop(recipient_9,recipient_age,15).
prop(recipient_10,recipient_age,53).
prop(recipient_11,recipient_age,28).
prop(recipient_12,recipient_age,15).
prop(recipient_13,recipient_age,32).
prop(recipient_14,recipient_age,61).
prop(recipient_15,recipient_age,16).
prop(recipient_16,recipient_age,16).
prop(recipient_17,recipient_age,28).
prop(recipient_18,recipient_age,37).
prop(recipient_19,recipient_age,9).
prop(recipient_20,recipient_age,33).
prop(recipient_21,recipient_age,64).
prop(recipient_22,recipient_age,65).
prop(recipient_23,recipient_age,7).
prop(recipient_24,recipient_age,31).
prop(recipient_25,recipient_age,40).
prop(recipient_26,recipient_age,44).
prop(recipient_27,recipient_age,3).
prop(recipient_28,recipient_age,28).
prop(recipient_29,recipient_age,62).
prop(recipient_30,recipient_age,1).

prop(recipient_1,recipient_HLA_A1,a96).
prop(recipient_2,recipient_HLA_A1,a33).
prop(recipient_3,recipient_HLA_A1,a56).
prop(recipient_4,recipient_HLA_A1,a53).
prop(recipient_5,recipient_HLA_A1,a14).
prop(recipient_6,recipient_HLA_A1,a17).
prop(recipient_7,recipient_HLA_A1,a2).
prop(recipient_8,recipient_HLA_A1,a24).
prop(recipient_9,recipient_HLA_A1,a94).
prop(recipient_10,recipient_HLA_A1,a43).
prop(recipient_11,recipient_HLA_A1,a35).
prop(recipient_12,recipient_HLA_A1,a48).
prop(recipient_13,recipient_HLA_A1,a99).
prop(recipient_14,recipient_HLA_A1,a65).
prop(recipient_15,recipient_HLA_A1,a42).
prop(recipient_16,recipient_HLA_A1,a20).
prop(recipient_17,recipient_HLA_A1,a93).
prop(recipient_18,recipient_HLA_A1,a17).
prop(recipient_19,recipient_HLA_A1,a29).
prop(recipient_20,recipient_HLA_A1,a100).
prop(recipient_21,recipient_HLA_A1,a91).
prop(recipient_22,recipient_HLA_A1,a63).
prop(recipient_23,recipient_HLA_A1,a27).
prop(recipient_24,recipient_HLA_A1,a28).
prop(recipient_25,recipient_HLA_A1,a45).
prop(recipient_26,recipient_HLA_A1,a47).
prop(recipient_27,recipient_HLA_A1,a93).
prop(recipient_28,recipient_HLA_A1,a26).
prop(recipient_29,recipient_HLA_A1,a39).
prop(recipient_30,recipient_HLA_A1,a76).

prop(recipient_1,recipient_HLA_A2,a67).
prop(recipient_2,recipient_HLA_A2,a97).
prop(recipient_3,recipient_HLA_A2,a18).
prop(recipient_4,recipient_HLA_A2,a95).
prop(recipient_5,recipient_HLA_A2,a60).
prop(recipient_6,recipient_HLA_A2,a91).
prop(recipient_7,recipient_HLA_A2,a33).
prop(recipient_8,recipient_HLA_A2,a44).
prop(recipient_9,recipient_HLA_A2,a8).
prop(recipient_10,recipient_HLA_A2,a50).
prop(recipient_11,recipient_HLA_A2,a94).
prop(recipient_12,recipient_HLA_A2,a100).
prop(recipient_13,recipient_HLA_A2,a25).
prop(recipient_14,recipient_HLA_A2,a97).
prop(recipient_15,recipient_HLA_A2,a99).
prop(recipient_16,recipient_HLA_A2,a71).
prop(recipient_17,recipient_HLA_A2,a59).
prop(recipient_18,recipient_HLA_A2,a66).
prop(recipient_19,recipient_HLA_A2,a40).
prop(recipient_20,recipient_HLA_A2,a56).
prop(recipient_21,recipient_HLA_A2,a56).
prop(recipient_22,recipient_HLA_A2,a83).
prop(recipient_23,recipient_HLA_A2,a34).
prop(recipient_24,recipient_HLA_A2,a92).
prop(recipient_25,recipient_HLA_A2,a68).
prop(recipient_26,recipient_HLA_A2,a94).
prop(recipient_27,recipient_HLA_A2,a35).
prop(recipient_28,recipient_HLA_A2,a93).
prop(recipient_29,recipient_HLA_A2,a21).
prop(recipient_30,recipient_HLA_A2,a52).

prop(recipient_1,recipient_HLA_B1,b96).
prop(recipient_2,recipient_HLA_B1,b97).
prop(recipient_3,recipient_HLA_B1,b91).
prop(recipient_4,recipient_HLA_B1,b24).
prop(recipient_5,recipient_HLA_B1,b73).
prop(recipient_6,recipient_HLA_B1,b96).
prop(recipient_7,recipient_HLA_B1,b44).
prop(recipient_8,recipient_HLA_B1,b74).
prop(recipient_9,recipient_HLA_B1,b40).
prop(recipient_10,recipient_HLA_B1,b74).
prop(recipient_11,recipient_HLA_B1,b4).
prop(recipient_12,recipient_HLA_B1,b34).
prop(recipient_13,recipient_HLA_B1,b36).
prop(recipient_14,recipient_HLA_B1,b100).
prop(recipient_15,recipient_HLA_B1,b100).
prop(recipient_16,recipient_HLA_B1,b80).
prop(recipient_17,recipient_HLA_B1,b22).
prop(recipient_18,recipient_HLA_B1,b26).
prop(recipient_19,recipient_HLA_B1,b14).
prop(recipient_20,recipient_HLA_B1,b8).
prop(recipient_21,recipient_HLA_B1,b67).
prop(recipient_22,recipient_HLA_B1,b28).
prop(recipient_23,recipient_HLA_B1,b13).
prop(recipient_24,recipient_HLA_B1,b81).
prop(recipient_25,recipient_HLA_B1,b40).
prop(recipient_26,recipient_HLA_B1,b34).
prop(recipient_27,recipient_HLA_B1,b66).
prop(recipient_28,recipient_HLA_B1,b62).
prop(recipient_29,recipient_HLA_B1,b76).
prop(recipient_30,recipient_HLA_B1,b24).

prop(recipient_1,recipient_HLA_B2,b96).
prop(recipient_2,recipient_HLA_B2,b18).
prop(recipient_3,recipient_HLA_B2,b7).
prop(recipient_4,recipient_HLA_B2,b46).
prop(recipient_5,recipient_HLA_B2,b15).
prop(recipient_6,recipient_HLA_B2,b51).
prop(recipient_7,recipient_HLA_B2,b78).
prop(recipient_8,recipient_HLA_B2,b44).
prop(recipient_9,recipient_HLA_B2,b98).
prop(recipient_10,recipient_HLA_B2,b34).
prop(recipient_11,recipient_HLA_B2,b13).
prop(recipient_12,recipient_HLA_B2,b87).
prop(recipient_13,recipient_HLA_B2,b64).
prop(recipient_14,recipient_HLA_B2,b29).
prop(recipient_15,recipient_HLA_B2,b90).
prop(recipient_16,recipient_HLA_B2,b80).
prop(recipient_17,recipient_HLA_B2,b29).
prop(recipient_18,recipient_HLA_B2,b2).
prop(recipient_19,recipient_HLA_B2,b25).
prop(recipient_20,recipient_HLA_B2,b6).
prop(recipient_21,recipient_HLA_B2,b26).
prop(recipient_22,recipient_HLA_B2,b4).
prop(recipient_23,recipient_HLA_B2,b5).
prop(recipient_24,recipient_HLA_B2,b78).
prop(recipient_25,recipient_HLA_B2,b40).
prop(recipient_26,recipient_HLA_B2,b48).
prop(recipient_27,recipient_HLA_B2,b56).
prop(recipient_28,recipient_HLA_B2,b16).
prop(recipient_29,recipient_HLA_B2,b65).
prop(recipient_30,recipient_HLA_B2,b87).

prop(recipient_1,recipient_HLA_DR1,dr27).
prop(recipient_2,recipient_HLA_DR1,dr14).
prop(recipient_3,recipient_HLA_DR1,dr9).
prop(recipient_4,recipient_HLA_DR1,dr26).
prop(recipient_5,recipient_HLA_DR1,dr11).
prop(recipient_6,recipient_HLA_DR1,dr27).
prop(recipient_7,recipient_HLA_DR1,dr27).
prop(recipient_8,recipient_HLA_DR1,dr16).
prop(recipient_9,recipient_HLA_DR1,dr1).
prop(recipient_10,recipient_HLA_DR1,dr28).
prop(recipient_11,recipient_HLA_DR1,dr13).
prop(recipient_12,recipient_HLA_DR1,dr5).
prop(recipient_13,recipient_HLA_DR1,dr6).
prop(recipient_14,recipient_HLA_DR1,dr18).
prop(recipient_15,recipient_HLA_DR1,dr13).
prop(recipient_16,recipient_HLA_DR1,dr2).
prop(recipient_17,recipient_HLA_DR1,dr4).
prop(recipient_18,recipient_HLA_DR1,dr24).
prop(recipient_19,recipient_HLA_DR1,dr18).
prop(recipient_20,recipient_HLA_DR1,dr27).
prop(recipient_21,recipient_HLA_DR1,dr25).
prop(recipient_22,recipient_HLA_DR1,dr4).
prop(recipient_23,recipient_HLA_DR1,dr6).
prop(recipient_24,recipient_HLA_DR1,dr28).
prop(recipient_25,recipient_HLA_DR1,dr9).
prop(recipient_26,recipient_HLA_DR1,dr1).
prop(recipient_27,recipient_HLA_DR1,dr25).
prop(recipient_28,recipient_HLA_DR1,dr14).
prop(recipient_29,recipient_HLA_DR1,dr25).
prop(recipient_30,recipient_HLA_DR1,dr12).

prop(recipient_1,recipient_HLA_DR2,dr11).
prop(recipient_2,recipient_HLA_DR2,dr16).
prop(recipient_3,recipient_HLA_DR2,dr19).
prop(recipient_4,recipient_HLA_DR2,dr13).
prop(recipient_5,recipient_HLA_DR2,dr26).
prop(recipient_6,recipient_HLA_DR2,dr14).
prop(recipient_7,recipient_HLA_DR2,dr5).
prop(recipient_8,recipient_HLA_DR2,dr24).
prop(recipient_9,recipient_HLA_DR2,dr9).
prop(recipient_10,recipient_HLA_DR2,dr11).
prop(recipient_11,recipient_HLA_DR2,dr18).
prop(recipient_12,recipient_HLA_DR2,dr26).
prop(recipient_13,recipient_HLA_DR2,dr23).
prop(recipient_14,recipient_HLA_DR2,dr18).
prop(recipient_15,recipient_HLA_DR2,dr7).
prop(recipient_16,recipient_HLA_DR2,dr15).
prop(recipient_17,recipient_HLA_DR2,dr1).
prop(recipient_18,recipient_HLA_DR2,dr27).
prop(recipient_19,recipient_HLA_DR2,dr14).
prop(recipient_20,recipient_HLA_DR2,dr6).
prop(recipient_21,recipient_HLA_DR2,dr15).
prop(recipient_22,recipient_HLA_DR2,dr24).
prop(recipient_23,recipient_HLA_DR2,dr18).
prop(recipient_24,recipient_HLA_DR2,dr26).
prop(recipient_25,recipient_HLA_DR2,dr24).
prop(recipient_26,recipient_HLA_DR2,dr9).
prop(recipient_27,recipient_HLA_DR2,dr28).
prop(recipient_28,recipient_HLA_DR2,dr4).
prop(recipient_29,recipient_HLA_DR2,dr8).
prop(recipient_30,recipient_HLA_DR2,dr13).

prop(recipient_1,recipient_once_a_donor,0).
prop(recipient_2,recipient_once_a_donor,0).
prop(recipient_3,recipient_once_a_donor,0).
prop(recipient_4,recipient_once_a_donor,1).
prop(recipient_5,recipient_once_a_donor,0).
prop(recipient_6,recipient_once_a_donor,0).
prop(recipient_7,recipient_once_a_donor,0).
prop(recipient_8,recipient_once_a_donor,0).
prop(recipient_9,recipient_once_a_donor,0).
prop(recipient_10,recipient_once_a_donor,0).
prop(recipient_11,recipient_once_a_donor,0).
prop(recipient_12,recipient_once_a_donor,0).
prop(recipient_13,recipient_once_a_donor,0).
prop(recipient_14,recipient_once_a_donor,1).
prop(recipient_15,recipient_once_a_donor,0).
prop(recipient_16,recipient_once_a_donor,0).
prop(recipient_17,recipient_once_a_donor,0).
prop(recipient_18,recipient_once_a_donor,0).
prop(recipient_19,recipient_once_a_donor,1).
prop(recipient_20,recipient_once_a_donor,0).
prop(recipient_21,recipient_once_a_donor,0).
prop(recipient_22,recipient_once_a_donor,0).
prop(recipient_23,recipient_once_a_donor,0).
prop(recipient_24,recipient_once_a_donor,0).
prop(recipient_25,recipient_once_a_donor,0).
prop(recipient_26,recipient_once_a_donor,0).
prop(recipient_27,recipient_once_a_donor,0).
prop(recipient_28,recipient_once_a_donor,0).
prop(recipient_29,recipient_once_a_donor,0).
prop(recipient_30,recipient_once_a_donor,0).

prop(recipient_1,recipient_PRA_percentage,41).
prop(recipient_2,recipient_PRA_percentage,42).
prop(recipient_3,recipient_PRA_percentage,42).
prop(recipient_4,recipient_PRA_percentage,20).
prop(recipient_5,recipient_PRA_percentage,26).
prop(recipient_6,recipient_PRA_percentage,40).
prop(recipient_7,recipient_PRA_percentage,11).
prop(recipient_8,recipient_PRA_percentage,30).
prop(recipient_9,recipient_PRA_percentage,99).
prop(recipient_10,recipient_PRA_percentage,81).
prop(recipient_11,recipient_PRA_percentage,95).
prop(recipient_12,recipient_PRA_percentage,3).
prop(recipient_13,recipient_PRA_percentage,72).
prop(recipient_14,recipient_PRA_percentage,36).
prop(recipient_15,recipient_PRA_percentage,22).
prop(recipient_16,recipient_PRA_percentage,90).
prop(recipient_17,recipient_PRA_percentage,75).
prop(recipient_18,recipient_PRA_percentage,82).
prop(recipient_19,recipient_PRA_percentage,42).
prop(recipient_20,recipient_PRA_percentage,1).
prop(recipient_21,recipient_PRA_percentage,44).
prop(recipient_22,recipient_PRA_percentage,17).
prop(recipient_23,recipient_PRA_percentage,17).
prop(recipient_24,recipient_PRA_percentage,24).
prop(recipient_25,recipient_PRA_percentage,12).
prop(recipient_26,recipient_PRA_percentage,17).
prop(recipient_27,recipient_PRA_percentage,19).
prop(recipient_28,recipient_PRA_percentage,18).
prop(recipient_29,recipient_PRA_percentage,2).
prop(recipient_30,recipient_PRA_percentage,26).



% kidney donor data
prop(kidney_1,donor_city,vancouver).
prop(kidney_2,donor_city,vancouver).
prop(kidney_3,donor_city,richmond).
prop(kidney_4,donor_city,burnaby).
prop(kidney_5,donor_city,vancouver).
prop(kidney_6,donor_city,burnaby).
prop(kidney_7,donor_city,vancouver).
prop(kidney_8,donor_city,surrey).
prop(kidney_9,donor_city,vancouver).
prop(kidney_10,donor_city,vancouver).

prop(kidney_1,donor_blood_type,ab).
prop(kidney_2,donor_blood_type,a).
prop(kidney_3,donor_blood_type,o).
prop(kidney_4,donor_blood_type,b).
prop(kidney_5,donor_blood_type,a).
prop(kidney_6,donor_blood_type,o).
prop(kidney_7,donor_blood_type,a).
prop(kidney_8,donor_blood_type,ab).
prop(kidney_9,donor_blood_type,a).
prop(kidney_10,donor_blood_type,o).

prop(kidney_1,donor_HLA_A1,a64).
prop(kidney_2,donor_HLA_A1,a80).
prop(kidney_3,donor_HLA_A1,a16).
prop(kidney_4,donor_HLA_A1,a65).
prop(kidney_5,donor_HLA_A1,a92).
prop(kidney_6,donor_HLA_A1,a41).
prop(kidney_7,donor_HLA_A1,a52).
prop(kidney_8,donor_HLA_A1,a20).
prop(kidney_9,donor_HLA_A1,a59).
prop(kidney_10,donor_HLA_A1,a97).

prop(kidney_1,donor_HLA_A2,a65).
prop(kidney_2,donor_HLA_A2,a92).
prop(kidney_3,donor_HLA_A2,a80).
prop(kidney_4,donor_HLA_A2,a47).
prop(kidney_5,donor_HLA_A2,a70).
prop(kidney_6,donor_HLA_A2,a57).
prop(kidney_7,donor_HLA_A2,a41).
prop(kidney_8,donor_HLA_A2,a73).
prop(kidney_9,donor_HLA_A2,a18).
prop(kidney_10,donor_HLA_A2,a97).

prop(kidney_1,donor_HLA_B1,b34).
prop(kidney_2,donor_HLA_B1,b63).
prop(kidney_3,donor_HLA_B1,b1).
prop(kidney_4,donor_HLA_B1,b46).
prop(kidney_5,donor_HLA_B1,b98).
prop(kidney_6,donor_HLA_B1,b39).
prop(kidney_7,donor_HLA_B1,b49).
prop(kidney_8,donor_HLA_B1,b22).
prop(kidney_9,donor_HLA_B1,b16).
prop(kidney_10,donor_HLA_B1,b70).

prop(kidney_1,donor_HLA_B2,b73).
prop(kidney_2,donor_HLA_B2,b68).
prop(kidney_3,donor_HLA_B2,b92).
prop(kidney_4,donor_HLA_B2,b3).
prop(kidney_5,donor_HLA_B2,b81).
prop(kidney_6,donor_HLA_B2,b24).
prop(kidney_7,donor_HLA_B2,b56).
prop(kidney_8,donor_HLA_B2,b1).
prop(kidney_9,donor_HLA_B2,b67).
prop(kidney_10,donor_HLA_B2,b48).

prop(kidney_1,donor_HLA_DR1,dr3).
prop(kidney_2,donor_HLA_DR1,dr1).
prop(kidney_3,donor_HLA_DR1,dr24).
prop(kidney_4,donor_HLA_DR1,dr26).
prop(kidney_5,donor_HLA_DR1,dr23).
prop(kidney_6,donor_HLA_DR1,dr17).
prop(kidney_7,donor_HLA_DR1,dr11).
prop(kidney_8,donor_HLA_DR1,dr19).
prop(kidney_9,donor_HLA_DR1,dr1).
prop(kidney_10,donor_HLA_DR1,dr11).

prop(kidney_1,donor_HLA_DR2,dr19).
prop(kidney_2,donor_HLA_DR2,dr17).
prop(kidney_3,donor_HLA_DR2,dr1).
prop(kidney_4,donor_HLA_DR2,dr28).
prop(kidney_5,donor_HLA_DR2,dr22).
prop(kidney_6,donor_HLA_DR2,dr2).
prop(kidney_7,donor_HLA_DR2,dr13).
prop(kidney_8,donor_HLA_DR2,dr28).
prop(kidney_9,donor_HLA_DR2,dr10).
prop(kidney_10,donor_HLA_DR2,dr18).

prop(kidney_1,donor_live,1).
prop(kidney_2,donor_live,0).
prop(kidney_3,donor_live,0).
prop(kidney_4,donor_live,0).
prop(kidney_5,donor_live,0).
prop(kidney_6,donor_live,0).
prop(kidney_7,donor_live,0).
prop(kidney_8,donor_live,1).
prop(kidney_9,donor_live,0).
prop(kidney_10,donor_live,0).